---

hospedate_mode: 
hospedate_project:                                         # client
hospedate_environment: integration                         #integration, production
hospedate_build_profile_customer: null
hospedate_build_profile_environment: integration
hospedate_build_user: awx-build
hospedate_build_group: "{{ hospedate_group_security }}"
hospedate_build_workspace: '/opt/workspace'
hospedate_build_workdir: "{{ hospedate_build_workspace }}/{{  hospedate_project }}/{{ hospedate_project }}-deploy-{{ hospedate_environment }}"
hospedate_build_sequence: "{{ hospedate_build_workspace }}/{{  hospedate_project }}/{{ hospedate_project }}-sequence-{{ hospedate_environment }}"
hospedate_build_sequence_file: "{{ hospedate_build_sequence }}/sequence.ini"

hospedate_build_repo_url: git@bitbucket.org:Swissbytes/syscom.git
hospedate_build_repo_branch: QA/COM-v2.13   #QA/COM-v2.13
hospedate_build_repo_filter: COM
hospedate_java_package_version: 'java-8'
hospedate_java_home: '/usr/lib64/jvm/jdk1.8.0_202'

hospedate_remote_user: awx-user
hospedate_remote_group: "{{ hospedate_group_security }}"
hospedate_remote_workdir: '/opt/.awx/deployments'
