---
- name: "Preoare to tranfer"
  block:

    - name: AWX BUILD SERVER - PREPARE PACKAGE - Checking hospedate_number_build
      debug:
        msg: "hospedate_number_build is {{ hospedate_number_build }}"

    - name: AWX BUILD SERVER - PREPARE PACKAGE - Checking inventory_hostname
      debug:
        msg: "hostname is {{ inventory_hostname }}"

    - name: "AWX BUILD SERVER - PREPARE PACKAGE - Delete previous /tmp/build_{{ hospedate_number_build }}"
      ansible.builtin.file:
        path: "/tmp/{{ hospedate_project }}_{{ hospedate_environment }}_build_{{ hospedate_number_build }}"
        state: absent
      ignore_errors: yes

    - name: "AWX BUILD SERVER - PREPARE PACKAGE - Create exists: /tmp/build_{{ hospedate_number_build }}"
      ansible.builtin.file:
        path: "/tmp/{{ hospedate_project }}_{{ hospedate_environment }}_build_{{ hospedate_number_build }}"
        state: directory
        owner: "{{ hospedate_build_user }}"
        group: "{{ hospedate_build_group }}"
        mode: 0775
        force: yes

    - name: "AWX BUILD SERVER - PREPARE PACKAGE - Move deploy.war to /tmp/build_{{ hospedate_number_build }}"
      ansible.builtin.shell: "cp {{ hospedate_build_workdir }}/target/*.war /tmp/{{ hospedate_project }}_{{ hospedate_environment }}_build_{{ hospedate_number_build }}/"

    - name: "AWX BUILD SERVER - PREPARE PACKAGE - Create compress file build_{{ hospedate_number_build }}.tar.gz "
      ansible.builtin.shell: "tar -zcvf {{ hospedate_project }}_{{ hospedate_environment }}_build_{{ hospedate_number_build }}.tar.gz {{ hospedate_project }}_{{ hospedate_environment }}_build_{{ hospedate_number_build }}" 
      args:
        chdir: "/tmp"

    - name: "AWX BUILD SERVER - PREPARE PACKAGE - Remove directory file build_{{ hospedate_number_build }} after compress"
      ansible.builtin.file:
        path: "/tmp/{{ hospedate_project }}_{{ hospedate_environment }}_build_{{ hospedate_number_build }}"
        state: absent
      ignore_errors: yes

    - name: DAWX BUILD SERVER - PREPARE PACKAGE - elete successfully fetched files
      file:
        path: buffer/
        state: absent    
        
    - name: AWX BUILD SERVER - PREPARE PACKAGE - Fetch the file from build localserver
      run_once: yes
      fetch: 
        src: "/tmp/{{ hospedate_project }}_{{ hospedate_environment }}_build_{{ hospedate_number_build }}.tar.gz"
        dest: buffer/ 
        flat: yes

    - name: AWX BUILD SERVER - PREPARE PACKAGE - Set to delegate variable from controller to COM-INTEGRATION
      set_fact:
        hospedate_number_build: "{{ hospedate_number_build }}"
        hospedate_project: "{{ hospedate_project }}"
        hospedate_environment: "{{ hospedate_environment }}"
      delegate_facts: yes
      delegate_to: com-integration
      when: hospedate_environment == 'integration'

    - name: AWX BUILD SERVER - PREPARE PACKAGE - Set to delegate variable from controller to COM-PRODUCTION
      set_fact:
        hospedate_number_build: "{{ hospedate_number_build }}"
        hospedate_project: "{{ hospedate_project }}"
        hospedate_environment: "{{ hospedate_environment }}"
      delegate_facts: yes
      delegate_to: com-production
      when: hospedate_environment == 'production'

  when: inventory_hostname == 'controller'

