galaxy_info:
  role_name: hospedate-jobs-backup
  namespace: middleware_automation
  author: Alexander Aguilar Torrico
  description: backup ...
  company: BolivianDevs.

  license: Apache License 2.0

  min_ansible_version: "2.9"

  platforms:
   - name: EL
     versions:
     - 8
     - 9

  galaxy_tags:
    - ubuntu
    - redhat
    - rhel
    - postgresql
    - databases
    - replications
