---

- name: "Backup  {{ hospedate_project|upper }} - {{ hospedate_environment|upper }} "
  block:

    - name: Print message if ansible version is greater than 2.7.0
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: "Get timestamp from the system"
      shell: "date +%Y%m%d-%H%M"
      register: tstamp

    - name: "Set variables"
      set_fact:
       my_date: "{{ tstamp.stdout[0:8]}}"
       my_time: "{{ tstamp.stdout[8:]}}"

    - name: "Backup On {{ hospedate_project|upper }} {{ hospedate_environment|upper }} - Ensure app workdir exists: {{ hospedate_local_workdir }}"
      become: yes
      ansible.builtin.file:
        path: "{{ hospedate_local_workdir }}"
        state: directory
        owner: "{{ hospedate_awx_user }}"
        group: "{{ hospedate_awx_group }}"
        mode: 0775
        force: yes

    - name: "Backup On {{ hospedate_project|upper }} {{ hospedate_environment|upper }} - Backup directory workdir exists: {{ hospedate_local_workdir }}/backup"
      ansible.builtin.file:
        path: "{{ hospedate_local_workdir }}/backup"
        state: directory
        owner: "{{ hospedate_awx_user }}"
        group: "{{ hospedate_awx_group }}"
        mode: 0775
        force: yes

    - name: "Backup On {{ hospedate_project|upper }} {{ hospedate_environment|upper }} - Log Directory workdir exists: {{ hospedate_local_workdir }}/log"
      ansible.builtin.file:
        path: "{{ hospedate_local_workdir }}/log"
        state: directory
        owner: "{{ hospedate_awx_user }}"
        group: "{{ hospedate_awx_group }}"
        mode: 0775
        force: yes

    - name: "Backup on {{ hospedate_project|upper }} {{ hospedate_environment|upper }} - Starting PGDUMP for backup"
      become_user: "{{ hospedate_awx_user }}"
      ansible.builtin.shell: "export PGPASSWORD={{ hospedate_db_local_password }} ; pg_dump -h {{ hospedate_db_local_host }} -U {{ hospedate_db_local_username }} {{ hospedate_db_local_exclude }}  -Fc {{ hospedate_db_local_name }} > {{ hospedate_db_local_name }}-{{ my_date }}{{ my_time }}.bkp "
      args:
        chdir: "{{ hospedate_local_workdir }}/backup"

    - name: "Backup On {{ hospedate_project|upper }} {{ hospedate_environment|upper }} - Finish backup "
      become_user: "{{ hospedate_awx_user }}"
      ansible.builtin.shell: "echo '{{ my_date }}{{ my_time }} [BACKUP] Creating backup {{ hospedate_local_workdir }}/backup/{{ hospedate_db_local_name }}-{{ my_date }}{{ my_time}}.bkp from the database {{ hospedate_db_local_name }}' >> {{ hospedate_local_workdir }}/log/backup.log"
