galaxy_info:
  role_name: hospedate-jobs-restart-backend
  namespace: middleware_automation
  author: Alexander Aguilar Torrico
  description: Hospedate Backend restart ...
  company: BoliviaDevs.

  license: Apache License 2.0

  min_ansible_version: "2.9"

  platforms:
   - name: EL
     versions:
     - 8
     - 9

  galaxy_tags:
    - amazon ami
    - redhat
    - rhel
    - tools
    - application
    - java
